### ISSUE TITLE
Review enhancements

### ISSUE THREAD

**Issue by jbrezmorf** [code-critic/codecritic#17]
- [x] Ability to resolve the review by other teacher, e.g. when student have technical problems.

- [x] add attempt details (student, date) to the header
![image](https://user-images.githubusercontent.com/326204/58954086-7806c880-8798-11e9-8e56-4f8fab9324aa.png)

- [x] BUG: wrong and over timelimit submission doesn't count into status
  Would help if the numbers of the status are colored: green, orange, red
![image](https://user-images.githubusercontent.com/326204/58954958-ea78a800-879a-11e9-8186-963bfecc96a3.png)

- [x] more compact view for filtered results:
  - language not important, often redundant
  - have one submission per line
  - add problem ID to the result field
  - ability to sort by name, or time
![image](https://user-images.githubusercontent.com/326204/58954389-5c4ff200-8799-11e9-9089-cdf933fa7254.png)

- [x] report also the runtime limit, e.g. 
  `WEBISL_case_6: 0.27   >0.25 Answer correct, over timelimit.`
![image](https://user-images.githubusercontent.com/326204/58954600-ee57fa80-8799-11e9-9723-06c75441006e.png)

- [x] view results: better now, but one submission per line would be better

**Comment by jbrezmorf** [comment]
- view results: better now, but one submission per line would be better
- colored score either use everywhere or nowhere
- still missing timelimit in results
- score still does not include other errors. We should possibly include all errors since otherwise, one could have only green score without passing all tests.

**Comment by janhybs** [comment]
You can now view diff @jbrezmorf 
![image](https://user-images.githubusercontent.com/894428/59151098-e0220c80-8a2d-11e9-8c8f-d0704ba91b2e.png)

**Comment by janhybs** [comment]
Added table-like view @jbrezmorf 
![image](https://user-images.githubusercontent.com/894428/59520572-8eb0cc00-8eca-11e9-9c31-5cfb4d497b2c.png)

**Comment by jbrezmorf** [comment]
Seems great. Going to test it soon.
