### ISSUE TITLE
Questions about config.yaml processing.

### ISSUE THREAD

**Issue by jbrezmorf** [code-critic/codecritic#27]
- [x]  Can we modify language detection form the script extension to detect Python 3 for the '*.py' and
    allowing to get use Python 2 only through the long variant?

- [x]  Is the 'size' key obligatory in the case of non '*.s' test id? It seems that the key is no obligatory, but then the test has no input.

- [x]  It seems that the submission is tested against all random inputs however the idea was 
    to test just single one randomly selected. The point is that the input set can be deterministic, but
    the student can not just optimize the code to a single particular input. 

- [x]  'random: R' variant. The test subscript should be passed to the script in order to allow 
setting of the random seed and obtain reproducible results. E.g. 

python3 -p 50 -r 7

to generate 'case-2.7'. The argument can be simply ignored by the script to get fully random results.

**Comment by jbrezmorf** [comment]
Resolution:

1. Drop support of Python 2. Use 'py' only for Python 3.
2. ??
3. Keep current bahavior of the 'random' key.
4. Pass the index of the subtest to the script. E.g.
    ```
    python3 main.py -p 50 -r 0
    ```
   will produce input file 'case-X.0'

**Comment by janhybs** [comment]
Index passing is now implemented, starting from `1` (as discussed on slack)
